# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "mac1" do |mac1|
    mac1.vm.box = "ramsey/macos-catalina"
    mac1.vm.network "public_network"
    mac1.vm.synced_folder ".", "/vagrant", disabled: true
    mac1.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  config.vm.define "mac2" do |mac2|
    mac2.vm.box = "ramsey/macos-catalina"
    mac2.vm.network "public_network"
    mac2.vm.synced_folder ".", "/vagrant", disabled: true
    mac2.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 2
    end
  end
end
